import type { Metadata } from "next";
import "./globals.css";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Blast War",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <Script
          src="https://telegram.org/js/telegram-web-app.js"
          strategy="beforeInteractive"
        />
      </head>
      <body className="bg-black">
        <main className="flex items-center justify-center min-h-screen">
          <div className="w-full max-w-md h-full">
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}
