import type { Metadata } from "next";
import "./globals.css";
export const metadata: Metadata = {
  title: "Blast War",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-black">
        <main className="flex items-center justify-center min-h-screen p-4">
          <div className="w-full max-w-md">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
